version: '3'

services:
  # DB
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library
    volumes:
      - mysql-data:/var/lib/mysql
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3

  # APP
  app:
     
    image: shonifari8/java-app:v1
    depends_on:
      database:
       condition: service_healthy

    ports:
      - "80:5000"

    environment:
       DB_HOST: "jdbc:mysql://database:3306/library"
       DB_USER: "root"
       DB_PASS: "password"
 

volumes:
  mysql-data:
  